Fix Dupe issue when pickup items
BG-Software-LLC/WildStacker pull request #401
Opened 2021-12-22 10:21 UTC by ssomar1607

2021-12-22 16:59 UTC, OmerBenGera requested changes

2021-12-22 16:59 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            else e.setCancelled(true);
Change it so instead of using else, check if EntityPickupItemEvent was cancelled, and if it was cancel PlayerAttemptsPickupItemEvent and then return

2021-12-22 18:16 UTC, ssomar1607 commented
Is it correct like that ?

2021-12-22 18:50 UTC, OmerBenGera requested changes

2021-12-22 18:50 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
There is no need for this check and the one below.
Remove the second one.

2021-12-22 19:18 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
Why you added it 10 days ago so ? ... https://github.com/BG-Software-LLC/WildStacker/commit/2fd34c41299af82049ef1b301efcdd6176f7e0ac

2021-12-22 20:40 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
> Why you added it 10 days ago so ? ... [2fd34c4](https://github.com/BG-Software-LLC/WildStacker/commit/2fd34c41299af82049ef1b301efcdd6176f7e0ac)

What?
You added a check if the event is canclled, then inside it you return. Therefore, there is no need to check again if its not cancelled - its redundant...

2021-12-22 20:58 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
Its not me its your code bro !

2021-12-22 20:58 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
You checked if the event isnt canceled and you recheck again the event !

2021-12-22 21:00 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
and you forgot to add a cancel event to the event PlayerAttemptPickupItemEvent If the event EntityPickupItemEvent is cancelled

2021-12-22 21:01 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
https://github.com/BG-Software-LLC/WildStacker/commit/2fd34c41299af82049ef1b301efcdd6176f7e0ac Just look your code

2021-12-22 21:08 UTC, ssomar1607 commented on src/main/java/com/bgsoftware/wildstacker/listeners/events/EventsListener.java
> +            if(bukkitEntityPickupItemEvent.isCancelled()){
> 
I just did what you said "Change it so instead of using else, check if EntityPickupItemEvent was cancelled, and if it was cancel PlayerAttemptsPickupItemEvent and then return" I kept your other check.
Now I dont have moe time. so Fix your plugin yourself.

2021-12-24 11:43 UTC, OmerBenGera approved these changes

2021-12-24 11:43 UTC, merged