Added upgrade menu lang
BG-Software-LLC/WildStacker pull request #426
Opened 2022-01-17 21:23 UTC by Superalex0102

2022-01-21 12:21 UTC, OmerBenGera requested changes
You haven't tested this before making the PR, were you?
Make sure you test it before you submit a PR for the next time.

2022-01-21 12:21 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildstacker/menu/SpawnerUpgradeMenu.java
> +                        .withName(Locale.UPGRADE_CURRENT + rawCurrentItemMeta.getDisplayName())
`Locale.UPGRADE_CURRENT`'s string is not the message itself.
Use Locale.UPGRADE_CURRENT#getMessage instead.

2022-01-21 12:21 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/wildstacker/menu/SpawnerUpgradeMenu.java
> +                        .withName(Locale.UPGRADE_NEXT + rawNextIcon.getItemMeta().getDisplayName())
`Locale.UPGRADE_NEXT`'s string is not the message itself.
Use Locale.UPGRADE_NEXT#getMessage instead.

2022-01-21 12:23 UTC, OmerBenGera requested changes

2022-01-21 12:23 UTC, OmerBenGera commented on src/main/resources/lang.yml
> +# Called on upgrade menu
"Used in the upgrades menu" or something like that may be better for describing these messages.

2022-01-23 11:40 UTC, Superalex0102 commented on src/main/java/com/bgsoftware/wildstacker/menu/SpawnerUpgradeMenu.java
> +                        .withName(Locale.UPGRADE_CURRENT + rawCurrentItemMeta.getDisplayName())
Sorry about that

2022-01-23 11:40 UTC, Superalex0102 commented on src/main/resources/lang.yml
> +# Called on upgrade menu
I wanted to use the same format, but okay

2022-01-23 20:36 UTC, OmerBenGera commented
I will test it on weekend and merge :)

2022-01-25 17:33 UTC, OmerBenGera commented
It's not possible to run the WildStacker that is compiled by your repository.
I don't like the fact that it's not possible to run it, and that you haven't even tested it.
I will merge it for this time, however in the future I will reject pull requests like this.

Thanks for helping tho, appreciated :)

2022-01-25 17:33 UTC, merged

2022-01-26 07:42 UTC, Superalex0102 commented
I did test it and had no issues this time, I even changed the lang in the file